# Generated by Django 2.2.4 on 2020-05-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flighttracker', '0002_article_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAVFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uav_no', models.CharField(max_length=8)),
                ('grs_job_no', models.CharField(max_length=8)),
                ('pm_name', models.CharField(max_length=50)),
                ('job_desc', models.CharField(max_length=255)),
                ('transferred_started', models.DateTimeField()),
                ('transferred_ended', models.DateTimeField()),
                ('pix4d_step_1_started', models.DateTimeField()),
                ('pix4d_step_1_ended', models.DateTimeField()),
                ('pix4d_step_2_started', models.DateTimeField()),
                ('pix4d_step_2_ended', models.DateTimeField()),
                ('pix4d_step_3_started', models.DateTimeField()),
                ('pix4d_step_3_ended', models.DateTimeField()),
                ('post_pix4d_started', models.DateTimeField()),
                ('post_pix4d_ended', models.DateTimeField()),
                ('errors', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
