# Generated by Django 2.2.4 on 2020-05-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flighttracker', '0003_auto_20200530_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uavflight',
            name='errors',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='uavflight',
            name='pix4d_step_1_ended',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='uavflight',
            name='pix4d_step_1_started',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='uavflight',
            name='pix4d_step_2_ended',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='uavflight',
            name='pix4d_step_2_started',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='uavflight',
            name='pix4d_step_3_ended',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='uavflight',
            name='pix4d_step_3_started',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='uavflight',
            name='pm_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uavflight',
            name='post_pix4d_ended',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='uavflight',
            name='post_pix4d_started',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='uavflight',
            name='transferred_ended',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='uavflight',
            name='transferred_started',
            field=models.DateTimeField(null=True),
        ),
    ]
