# Generated by Django 2.2.4 on 2020-05-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flighttracker', '0004_auto_20200530_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='uavflight',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
